### ISSUE TITLE
How to install the SimpleUploadAdapter plugin?

### ISSUE THREAD

**Issue by dregos** [ckeditor/ckeditor5-angular#150] opened 2019-10-16 05:31 UTC
CKEditor5 in Angular 8 with image upload plugin and file upload. I am loosing it. Been at it a few days and whatever I do I get some kind of error. 
I need CKEditor classic build and most importantly to be able to upload images and files by sending them to my service for upload(setting my own url for uploads). I would appreciate step by step instructions so I don't miss something.
This is my environment:
- Angular CLI: 8.0.1
- Node: 8.14.0
- npm: 6.12.0

I have read all the documentation from CKEditor but as if some step is always missing. Maybe I am missing or don't understand something. My latest try is from this [How to enable image upload support in CKEditor 5?](https://stackoverflow.com/questions/46765197/how-to-enable-image-upload-support-in-ckeditor-5)
Steps I did are:

1. cloned ckeditor5-build-classic
2.  In the ckeditor5-build-classic project directory ran
3. `npm i`
4. `npm install --save @ckeditor/ckeditor5-upload`
> Here I see a potential problem. For every import, ones that come with the build and my new ones I get 'Could not find a declaration file for module'. 
5. `import SimpleUploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/simpleuploadadapter';`
6. `npm run build`
7. copied ./build/ckeditor.js to my angular project
8.  Added CKEditor to my project:
9. tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "allowJs": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```
10. In the component:
```
import * as ClassicEditor from '../../../../ext/plugins/ckeditor.js';
public Editor = ClassicEditor;
public editorConfig = {
     simpleUpload: {
         // The URL that the images are uploaded to.
         uploadUrl: this.url
     }
 }
```
HTML:
```
<ckeditor
     [editor]="Editor"
     [config]="editorConfig"
     name="ckeBody"
     id="editor"
     [(ngModel)]="doc.Body"
     >
</ckeditor>
```

And with this latest try I get an error:

> _ckeditor-ckeditor5-angular.js:326 TypeError: Cannot read property 'rootName' of undefined_

**Comment by ma2ciek** [comment] 2019-10-22 09:45
@dregos, could you check if it's not a duplicate of https://github.com/ckeditor/ckeditor5-angular/issues/20?

**Comment by dregos** [comment] 2019-10-22 10:10
It seems that #20 is the solution. Will try it. But now I've tried a different approach but am only able to upload images for now. 
1. Installed npm install --save @ckeditor/ckeditor5-angular, npm install --save @ckeditor/ckeditor5-build-classic
2. Created the Custom upload adapter. 
- see the file attached - row 55
[CKECustomUploadAdapter.txt](https://github.com/ckeditor/ckeditor5-angular/files/3754843/CKECustomUploadAdapter.txt)

3. Added OnReady
`    public onReady( editor ) {
      editor.ui.getEditableElement().parentElement.insertBefore(
        editor.ui.view.toolbar.element,
        editor.ui.getEditableElement()
      );
      editor.plugins.get('FileRepository').createUploadAdapter = (loader)=> {
        return new CKEUploadAdapter(loader, uploadUrl);
      };
    }`
When trying to upload via upload url then it doesn't work. Check Upload func. When Uploading base64 then I get the image encoded in editor, which is ok. I can work with that. 
Can I do the same with files? Can I do a custom file uploader not just images?

**Comment by ma2ciek** [comment] 2019-10-22 10:37
Please, use triple ` for code blocs highlighting - https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.

> @Injectable()

This won't work. It's not an Angular component. Probably that's why the whole class doesn't work as expected.

**Closed** 2019-11-05 08:35 UTC
Labels: pending:feedback, type:question

**Comment by chandiralekhasankar** [comment] 2020-04-30 13:20
In CKEditor 5 **"Bold"**(most of the toolbar functionalities) function is not working in classic Editor, is it need any specific toolbar configuration or dependencies for angular 8?
