### ISSUE TITLE
ngModel binding does not set initial value

### ISSUE THREAD

**Issue by pmacn** [ckeditor/ckeditor5-angular#265] opened 2021-06-25 19:17 UTC
When using ngModel binding with CKEditor the editor is always empty

Versions
`ckeditor@28.0.0`
`ckeditor/ckeditor5-angular@2.0.1`

To replicate, use the following component

``` html
<ckeditor [editor]="Editor" [(ngModel)]="content"></ckeditor>
```

``` typescript
import { Component } from '@angular/core';
import * as ClassicEditor from './ckeditor.js'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  public content: string = 'This is content';
  public Editor = ClassicEditor;
}
```

This seems to be a timing issue and my current workaround is to call setData in the ready action like so

``` html
<ckeditor #editor [editor]="Editor" (ready)="onEditorReady($event)" [(ngModel)]="content"></ckeditor>
```

``` typescript
import { Component, ViewChild } from '@angular/core';
import { CKEditorComponent } from '@ckeditor/ckeditor5-angular';
import * as ClassicEditor from './ckeditor.js'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  public content: string = 'This is content';
  public Editor = ClassicEditor;
  @ViewChild('editor')
  editor!: CKEditorComponent;

  public onEditorReady(event: any) {
    setTimeout(() => {
      this.editor.editorInstance?.setData(this.content);
    }, 0);
  }
}

```

**Comment by ma2ciek** [comment] 2021-06-25 21:37
Hi @pmacn,

This is probably a duplicate of ckeditor/ckeditor5#9620 and will be fixed next week.

**Closed** 2021-06-28 14:22 UTC
