### ISSUE TITLE
Toolbar is hidden in the context menu when used in a  matDialog

### ISSUE THREAD

**Issue by Neill83** [ckeditor/ckeditor5-angular#293] opened 2022-01-19 15:54 UTC
Hi, the toolbar is hidden when initialized
![image](https://user-images.githubusercontent.com/9987324/150166729-8b5d25c4-0585-453e-9cd5-0b13677e8fc6.png)

this can be fixed by doing the following, but this is not the expected behaviour...
![image](https://user-images.githubusercontent.com/9987324/150166620-c5805e46-5024-4137-9b43-f386e7273985.png)

and another bug is that the toolbar is not visible when content is too small
![image](https://user-images.githubusercontent.com/9987324/150166976-59e30959-7e93-4b9a-bcfb-e8b6d6ce2809.png)

Thanks.

**Comment by FilipTokarski** [comment] 2022-01-24 08:16
Looks like a duplicate of https://github.com/ckeditor/ckeditor5/issues/9763 and https://github.com/ckeditor/ckeditor5/issues/10939.

**Comment by pomek** [comment] 2022-06-10 09:15
Closing as DUP ☝️.

**Closed by pomek** 2022-06-10 09:15 UTC
