### ISSUE TITLE
Custom build for BalloonEditor give Uncaught CKEditor Error: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated

### ISSUE THREAD

**Issue by nikunjbanker** [ckeditor/ckeditor5-angular#136] opened 2019-08-28 17:22 UTC
I have created custom build from source by following steps given at [Advance setup](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html) - I am using Super Build having BalloonBlockEditor and BalloonEditor.

Git repo location of the custom build: (https://github.com/nikunjbanker/ckeditor-custom-build). Please perform npm i, after taken source from above location. Ref. I took inspiration from [real-time-collaboration-for-angular](https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-angular)

I have created enjoin-ckeditor.js file, it containing information about my custom build with additional plugins and its default build configuration. So, this super build exporting two object, BalloonBlockEditor and BalloonEditor. All the dependencies of the custom build and extra plugins also added in package.json file.

To build this super custom build, I have created webpack.config.js, containing information about how to build it with its all dependencies with languages support as well. And, It's exporting library as 'CKEDITOR'.

I am able to generate build using command 'yarn run build'. But, when I am referring it in my angular project. It is given error on start project:

> Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

In angular project, I am referring angular package - @ckeditor/ckeditor5-angular. And, in the component where I want to use it, its imported as 'js' file from above super custom build output build as follow:

```
import * as CKEDITOR from '../../../../vendor/ckeditor5/build/enjoin-editor.js';
import '../../../../vendor/ckeditor5/build/translations/en.js';

 <ckeditor [(ngModel)]="model.data" [editor]="Editor" (change)="onChange($event, model)"></ckeditor>
```

Note: I have already verified in my custom build. I am not mixing with build-balloon and balloon. Everywhere, I am referring class from 'src' folder.  I am not mistakenly imported a build instead of the source BalloonEditor. 

It seems, there is some issue with custom super build using source balloon editor. 

I might be wrong and it might be my mistake as well. Any help in solution will be appreciated @Reinmar

**Comment by Mgsy** [comment] 2019-09-02 08:55
@ma2ciek, can you take a look at this one?

**Comment by nikunjbanker** [comment] 2019-09-13 14:10
Hi @ma2ciek,

Yes, I am using only one CKEditor 5 package in my whole application. 

> I've followed your installation steps and both editors in the angular app work fine.

Can you please share your git repository containing source, where you are able to make it working - both super custom build and angular app where you are utilizing it.

Regards,
Nikunj

**Comment by ma2ciek** [comment] 2019-09-13 14:30
Here's the code I used to reproduce the issue: https://github.com/ckeditor/ckeditor5-angular/compare/t/136. The `superbuild.js` file is the result of building the https://github.com/nikunjbanker/ckeditor-custom-build.

**Comment by ma2ciek** [comment] 2019-09-26 15:38
I'm closing due to lack of interest. Feel free to comment if you still have a problem.

**Closed by ma2ciek** 2019-09-26 15:38 UTC
Labels: pending:feedback
