### ISSUE TITLE
Getting TypeError: Cannot read property '0' of undefined, when creating custom plugin

### ISSUE THREAD

**Issue by seaniemc** [ckeditor/ckeditor5-angular#137] opened 2019-09-24 08:59 UTC
I am trying to add a custom plugin to add to the ckeditor5-build-decoupled-document editor. When I add my custom plugin to the ckeditor5-build-decoupled-document build code and then running `npm run build`. But I get the error `TypeError: Cannot read property '0'` of undefined when I add the ckeditor.js build file to my angular project.

![failure](https://user-images.githubusercontent.com/9398358/65504829-bd721180-debf-11e9-9862-681fd7e39626.PNG)

The editor toolbar is no longer displayed on the screen and I cannot edit the text, however, the plugin is performing its purpose of allowing inline style in the editor. 

I have 2 questions:

1. Have I created the plugin correctly?
2. Is there something missing from my configuration within my Angular project?

These are the steps I followed and the code used. 

```
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';

export default class Extension extends Plugin {
    constructor( editor ) {
		super( editor );
	}

    init() {
        const editor = this.editor;

        let allowedAttributes = [
            'width', 'height', 'style', 'stylex', 'target', 'class', 'id', 'name', 'title', 'type', 'olddisplay', 'text-align', 'align',
            'border', 'cellspacing','padding', 'cellpadding', 'color', 'valign', 'clear', 'src',  'shapes', '&amp',
            'prefix', 'tagtype', 'datetime', 'cite',  'cols', 'colspan', 'noshade', 'text-decoration',
            'shape', 'start',  'alt', 'strong', 'files', 'hr', 'font-size',
            'com',  'background-color', 'rowspan', 'span', 'page', 'content',
            'action', 'value', 'autofocus', 'maxlength', 'rows', 'for', 'aria-label', 'checked', 'selected',
            'rel', 'scope', 'location', 'cellpacing', 'block-id', 'lang',
            'original-style', 'datatype', 'property', 'controls', 'controlslist', 'data-attr', 'poster', 'preload',
            'tabindex', 'role', 'aria-describedby', 'aria-disabled','aria-haspopup', 
            'href', 'col', 'doc', 'attach', 'pls', 'vspace', 'hspace', 'slatepath'];
    
         //creates a new schema to to keep preexisting styles
         editor.model.schema.extend('$root', { allowAttributes: allowedAttributes });
         editor.model.schema.extend('$block', { allowAttributes: allowedAttributes });
         editor.model.schema.extend('$text', { allowAttributes: allowedAttributes });
     
         for (var i = 0; i < allowedAttributes.length; i++) {
             editor.conversion.attributeToAttribute({ model: this.allowedAttributes[i], view: this.allowedAttributes[i] });
         }
     
         editor.model.schema.extend('paragraph', { allowAttributes: '__style' });
     
         editor.conversion.for('upcast').attributeToAttribute({
             model: {
                 key: '__style',
                 name: 'paragraph'
             },
             view: 'style'
         });
     
         editor.conversion.for('downcast').add(dispatcher => {
             dispatcher.on('attribute:__style:paragraph', (evt, data, conversionApi) => {
                 conversionApi.consumable.consume(data.item, evt.name);
     
                 const viewElement = conversionApi.mapper.toViewElement(data.item);
       
                 conversionApi.writer.setAttribute('style', data.attributeNewValue, viewElement);
             });
         });
    } 
}
```

I then added the plugin to the ckeditor.js file 

`import Extension from "../ckeditor5-extension/src/extension.js";`

```
DecoupledEditor.builtinPlugins = [
	...
	Table,
	TableToolbar,
	Extension
];
```
Following this, I run `npm run build` which generates the ckeditor.js in the build folder. 

Next, I copied the ckeditor.js (and corresponding translation files ) from the build folder into the assets folder of my angular project.

Then add my custom editor to my file.
`import * as CustomEditor from 'src/assets/ckeditor.js';`
 `public Editor = CustomEditor;`

In the tsconfig.json 
```
"compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowJs": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
```
In the console when I print out the plugins for the editor my custom plugin is showing undefined. 
`["Essentials", "Alignment", "FontSize", "FontFamily", "Highlight", "CKFinderUploadAdapter", "Autoformat", "Bold", "Italic", "Strikethrough", "Underline", "BlockQuote", "CKFinder", "EasyImage", "Heading", "Image", "ImageCaption", "ImageStyle", "ImageToolbar", "ImageUpload", "Link", "List", "MediaEmbed", "Paragraph", "PasteFromOffice", "Table", "TableToolbar", undefined]`

Any help with this issue would be great.

**Comment by seaniemc** [comment] 2019-09-24 12:04
@Mgsy or @ma2ciek  can you have a look at this when you get the time?

Thanks, Sean.

**Comment by ma2ciek** [comment] 2019-09-26 14:06
Hi @seaniemc,

Since the plugin is `undefined`, it looks like the issue might be not connected to the Angular at all. Have you tried to open the sample that is in the  `ckeditor5-build-decoupled-document/sample/index.html` after the building step? I guess that this would narrow the problem as this kind of error can be a result of the incorrect transpilation too/.

On the other hand we provide the name of the plugin using the `pluginName`, but not providing it should not be an issue here.

```js
class CustomPlugin {
	static get pluginName() {
		return 'CustomPlugin';
	}
}
```

**Comment by seaniemc** [comment] 2019-09-27 09:39
@ma2ciek. 
Thanks for that, the error was in fact caused by the code in the plugin. 

`editor.conversion.attributeToAttribute({ model: this.allowedAttributes[i], view: this.allowedAttributes[i] });`

We were calling `this.allowedAttributes[i]` when it should be `allowedAttributes[i]`

After sorting that issue the editor loads the plugin is created correctly but we are getting the following error

![plugin-error](https://user-images.githubusercontent.com/9398358/65759423-cc9ccd80-e112-11e9-8d04-8d96322d595f.PNG)

Which is down the way my plugin is performing the conversion.

**Comment by ma2ciek** [comment] 2019-09-27 13:50
Since the issue is mainly connected with the implementation of your custom plugin, not with the angular integration, could you repost the issue in the main https://github.com/ckeditor/ckeditor5 issue tracker? It will get more traction there.

Have you also seen the explanation in the https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-conversion-attribute-to-attribute-on-text?

**Comment by ma2ciek** [comment] 2019-10-11 12:16
I'm closing since the issue is not relevant to this repository.

**Closed by ma2ciek** 2019-10-11 12:16 UTC
Labels: pending:feedback
