### ISSUE TITLE
Production build broken with version 1.1.2 and Angular 5.2.9

### ISSUE THREAD

**Issue by francescoben** [ckeditor/ckeditor5-angular#155] opened 2019-11-07 16:26 UTC
Hi,
I'm using the latest version of this module (1.1.2) and Angular 5.2.9 but the production build breaks the plugin, this is the error I get in the console when I load a page that contains the ckeditor:

`CKEditorError: unexpected-error {"originalError":{"message":"Cannot access 'n' before initialization","stack":"ReferenceError: Cannot access 'n' before initialization\n    at http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:5120861\n    at Gr (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:5120935)\n    at Zr (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:5120737)\n    at http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:5120602\n    at he._callPostFixers (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:4921751)\n    at bi.change (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:4976501)\n    at bi._disableRendering (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:4977177)\n    at xr.listenTo.priority (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:5032570)\n    at xr.fire (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:4885586)\n    at xr._runPendingChanges (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:5114958)","name":"ReferenceError"}}
    at Function.rethrowUnexpectedError (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:4791854)
    at bi.change (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:4976598)
    at bi._disableRendering (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:4977177)
    at xr.listenTo.priority (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:5032570)
    at xr.fire (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:4885586)
    at xr._runPendingChanges (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:5114958)
    at xr.enqueueChange (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:5110654)
    at Io.init (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:5053940)
    at Io.<anonymous> (http://angular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:4899929)
    at Io.fire (http://iangular.loc:4202/main.ad38b4b091d0ac5657da.bundle.js:1:4885586)`

Has anyone encountered the same problem?
Thanks

**Comment by ma2ciek** [comment] 2019-11-07 17:58
Hi @francescoben,

Looking at the stack trace I guess that the error might be caused because of the incorrect transpilation of CKEditor 5 code, not the integration itself. Could you check whether your problem occurs with the older CKEditor 5 build, e.g. with the 12.4.0 version? 

If you still have problems with the previous versions, then could you list your dependencies of the Angular project so I can reproduce the error?

**Comment by francescoben** [comment] 2019-11-08 08:47
hi @ma2ciek, I will to downgrade `@ckeditor/ckeditor5-build-classic` to the 12.4.0 version and I'll let you know! Thanks for your help :+1:

**Comment by francescoben** [comment] 2019-11-08 11:46
@ma2ciek unfortunately the downgrade didn't work, we tried `12.4.0` and even `11.2.0` without any results, we got the same error.
Here's the list of my current dependencies:
```
 "dependencies": {
    "@agm/core": "1.0.0-beta.2",
    "@angular/animations": "5.2.9",
    "@angular/cdk": "5.1.0",
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/material": "5.1.0",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@angular/platform-server": "5.2.9",
    "@angular/router": "5.2.9",
    "@auth0/angular-jwt": "1.0.0-beta.9",
    "@ckeditor/ckeditor5-angular": "1.1.2",
    "@ckeditor/ckeditor5-build-classic": "15.0.0",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-beta.9",
    "@ng-select/ng-select": "1.6.3",
    "@types/smoothscroll-polyfill": "0.3.1",
    "@vimeo/player": "2.2.1",
    "angular2-jwt": "0.2.3",
    "bootstrap": "4.0.0-beta",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.3",
    "d3": "4.12.2",
    "file-saver": "2.0.2",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "intl": "1.2.5",
    "js-video-url-parser": "0.4.0",
    "marked": "0.3.12",
    "masonry-layout": "4.2.1",
    "moment": "2.22.2",
    "moment-timezone": "0.5.17",
    "ngx-clipboard": "9.1.3",
    "ngx-facebook": "2.4.0",
    "ngx-masonry": "1.1.2",
    "ngx-moment": "3.1.0",
    "ngx-swiper-wrapper": "4.8.0",
    "ngx-webstorage-service": "3.1.3",
    "pdfmake": "0.1.60",
    "popper.js": "1.12.9",
    "progressbar.js": "1.0.1",
    "rxjs": "5.5.6",
    "smoothscroll-polyfill": "0.4.4",
    "underscore": "1.8.3",
    "url-polyfill": "1.0.13",
    "web-animations-js": "2.3.1",
    "zingchart": "2.6.1",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.7.4",
    "@angular/compiler-cli": "5.2.9",
    "@angular/language-service": "4.4.6",
    "@types/file-saver": "2.0.1",
    "@types/google.analytics": "0.0.36",
    "@types/hammerjs": "2.0.35",
    "@types/jasmine": "2.5.54",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "6.0.96",
    "codelyzer": "4.1.0",
    "css": "2.2.3",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "jscpd": "0.6.17",
    "karma": "4.1.0",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.3",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-phantomjs-launcher": "1.0.4",
    "karma-spec-reporter": "0.0.32",
    "npm-run-all": "4.1.2",
    "protractor": "5.4.2",
    "protractor-jasmine2-screenshot-reporter": "0.5.0",
    "ts-node": "3.3.0",
    "tslint": "5.9.1",
    "typescript": "2.6.2",
    "webpack-bundle-analyzer": "3.3.2"
  }
```

**Comment by ma2ciek** [comment] 2019-11-08 12:31
Oh...

I'll try to reproduce it. 

Could you show also the configuration of the `<ckeditor>` component?

Also, do you target `ES6` in the `tsconfig.json`? Targeting `ES5` leads to incorrect transpilations quite often, especially combined with the minifier (as I assume this can cause the issue as it's the production build only issue).

**Comment by ma2ciek** [comment] 2019-11-08 14:12
If the problem still occurs after the above change then please use the `@ckeditor/ckeditor5-angular` to the `1.1.0` version for now.

**Comment by ma2ciek** [comment] 2019-11-08 14:30
I've installed the above packages and everything is working fine for me.

See https://github.com/ma2ciek/ckeditor5-angular-test/tree/angular-5.

I've to add the following missing packages to the package.json file in order to compile:
- "webpack": "^3.12.0",
- "@angular-devkit/build-optimizer": "^0.803.18",

This means that the problem is rather specific to the CKEditor 5 configuration and some unfortunate transpilation in which probably I can't help you directly since I can't reproduce the error.

**Comment by paolomainardi** [comment] 2019-11-11 13:53
Hi @ma2ciekm thanks for your quick feedback, just following up the bug issues by @francescoben.

I've isolated the piece of code that transpiled gives the error:

```javascript
            n.prototype.createEditor = function() {
                var n = this
                  , t = document.createElement(this.tagName);
                if (this.editorElement = t,
                this.data && this.config.initialData)
                    throw new Error("Editor data should be provided either using `config.initialData` or `data` properties.");
                var e = Object(u.__assign)({}, this.config, {
                    initialData: this.config.initialData || this.data || ""
                });
                return this.elementRef.nativeElement.appendChild(t),
                this.editor.create(t, e).then(function(t) {
                    n.editorInstance = t,
                    n.initialIsDisabled && (t.isReadOnly = n.initialIsDisabled),
                    n.ngZone.run(function() {
                        n.ready.emit(t)
                    }),
                    n.setUpEditorEvents(t)
                }).catch(function(n) {
                    // ERROR CATCHED HERE.
                    console.error(n.stack)
                })
            }
```

As you can see the error is related somewhere in the incorrect transpiling. do you have any ideas of what is happening there ? In the meantime i continue to investigate further.

**Comment by paolomainardi** [comment] 2019-11-11 14:53
The fun fact is that the editor is rendered and barely working:

<img width="761" alt="Screenshot 2019-11-11 at 15 50 48" src="https://user-images.githubusercontent.com/8747/68596309-4d354480-049b-11ea-80c3-83fdbd2f3623.png">

But when trying to use it:

```
polyfills.c7f5778c5a2a9122044c.bundle.js:1 Uncaught CKEditorError: cannot-change-view-tree: Attempting to make changes to the view when it is in an incorrect state: rendering or post-fixers are in progress. This may cause some unexpected behavior and inconsistency between the DOM and the view. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-cannot-change-view-tree

    at bi.change (http://ckeditor.loc:4202/main.04ddb1fc7c64ad2055f8.bundle.js:1:4972805)
    at bi.forceRender (http://ckeditor.loc:4202/main.04ddb1fc7c64ad2055f8.bundle.js:1:4973476)
    at bi.focus (http://ckeditor.loc:4202/main.04ddb1fc7c64ad2055f8.bundle.js:1:4972715)
    at ka.<anonymous> (http://ckeditor.loc:4202/main.04ddb1fc7c64ad2055f8.bundle.js:1:5275148)
    at ka.fire (http://ckeditor.loc:4202/main.04ddb1fc7c64ad2055f8.bundle.js:1:4882372)
    at Mt (http://ckeditor.loc:4202/main.04ddb1fc7c64ad2055f8.bundle.js:1:4883447)
    at Ya.fire (http://ckeditor.loc:4202/main.04ddb1fc7c64ad2055f8.bundle.js:1:4882556)
    at Mt (http://ckeditor.loc:4202/main.04ddb1fc7c64ad2055f8.bundle.js:1:4883447)
    at Pa.fire (http://ckeditor.loc:4202/main.04ddb1fc7c64ad2055f8.bundle.js:1:4882556)
    at Jr.<anonymous> (http://ckeditor.loc:4202/main.04ddb1fc7c64ad2055f8.bundle.js:1:5141827)
```

**Comment by paolomainardi** [comment] 2019-11-11 18:24
I've finally succeded to reproduce a simple test case: https://github.com/ma2ciek/ckeditor5-angular-test/pull/6/files which is basically changing the ckeditor configurations, the culprit seems to be the `placeholder` attribute.

You can find the PR here: https://github.com/ma2ciek/ckeditor5-angular-test/pull/6/files

**Comment by ma2ciek** [comment] 2019-11-12 10:07
Hi @paolomainardi,

Yes, indeed, there's a problem with old Angular versions while working with the placeholder attribute - that's because of the incorrect minifier transpilation, this is a 3rd party lib bug - https://github.com/ckeditor/ckeditor5-angular/issues/157, https://github.com/ckeditor/ckeditor5/issues/1758. You can fix it probably only by upgrading your Angular devkit.

Duplicate of https://github.com/ckeditor/ckeditor5/issues/1758.

**Closed by ma2ciek** 2019-11-12 10:07 UTC
Labels: pending:feedback
