### ISSUE TITLE
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-angular/ckeditor-ckeditor5-angular'

### ISSUE THREAD

**Issue by BeatMercy** [ckeditor/ckeditor5-angular#78] opened 2019-03-09 04:35 UTC
I just got a complier error on using  "Module not found: Error: Can't resolve '@ckeditor/ckeditor5-angular/ckeditor.component'" on using
```
@ViewChild('ckeditor')
  editor: CKEditorComponent
```
for ovserving the change event

I import it as vscode auto import do.
`import { CKEditorComponent } from '@ckeditor/ckeditor5-angular/ckeditor.component'`
html template
```
<ckeditor #ckeditor
              [editor]="Editor"
              [config]="editorConfig"
              [(ngModel)]="publication.content"
              (ready)="onEditorReady($event)">
</ckeditor>
```

these are my dependencies

```
"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^7.3.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^7.3.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3"
}
```

```
"devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "~6.0.8",
    "@angular/compiler-cli": "^6.0.3",
    "@ckeditor/ckeditor5-alignment": "^11.0.0",
    "@ckeditor/ckeditor5-angular": "^1.0.1",
}
```

**Comment by BeatMercy** [comment] 2019-03-09 04:39
app.module.ts
`import { CKEditorModule } from '@ckeditor/ckeditor5-angular'`
the NgModule
```
imports: [
...
    CKEditorModule,
...
]
```

PS: editor run well before Added the CKEditorComponent

**Comment by ma2ciek** [comment] 2019-03-11 22:56
Hi @BeatMercy!

You probably used `CKEditorComponent` as a value, not as a type somewhere. Note that the `CKEditorComponent` is exported there as a type only (`export declare class CKEditorComponent { ... }`).

But I'm not sure why it doesn't have corresponding JS file there though (builds for specific envs are present there in the specific directories) - for me it looks like an `ng-packagr` issue. I'll try to ensure that it won't happen in the next release of `ckeditor5-angular`.

**Comment by Mgsy** [comment] 2019-03-26 10:15
Closing it due to a lack of activity.

**Comment by andycrulez** [comment] 2019-04-09 08:27
I have exactly the same problem, is there an existing solution?

**Comment by ma2ciek** [comment] 2019-04-09 08:35
Could you describe how you use the `CKEditorComponent`?

**Comment by ma2ciek** [comment] 2019-04-09 08:39
Ok, I was able to reproduce it.

**Comment by andycrulez** [comment] 2019-04-09 08:40
I have multiple instances of my custom inline editor. The goal was to get the instances of the editors and work with them further.

Usage:
`import { CKEditorComponent } from '@ckeditor/ckeditor5-angular/ckeditor.component';
...
@ViewChildren(CKEditorComponent) editors: QueryList<CKEditorComponent>;`

I hope that the angular part is fine. I'm quite new in it...

**Comment by ma2ciek** [comment] 2019-04-09 08:41
It's because Angular tries to get some metadata with the usage of decorators.

```js
public editorComponent: CKEditorComponent; // no error

@ViewChild( 'ckeditor1' ) editorComponent: CKEditorComponent; // error
```

**Comment by ma2ciek** [comment] 2019-04-09 08:54
Actually, I've checked and the editor on the `master` branch works properly, so I'll close this issue and will try to release it soon.

Note that after the release these imports will change:

`import { CKEditorComponent } from '@ckeditor/ckeditor5-angular/ckeditor.component';` -> `import { CKEditorComponent } from '@ckeditor/ckeditor5-angular';`

`import { CKEditor5 } from '@ckeditor/ckeditor5-angular/ckeditor';` -> `import { CKEditor5 } from '@ckeditor/ckeditor5-angular';`

They will point the existing file, so the issue won't exist anymore.

**Closed by ma2ciek** 2019-04-09 08:54 UTC
Labels: type:bug

**Comment by BeatMercy** [comment] 2019-04-09 09:27
well, there is a temporary solution. 🙃
```
 @ViewChild('articleEditor')
  editor: any
...
  public onEditorReady(editor) {
    this.editor.change
      .pipe(debounceTime(3000))
      .subscribe(
        changeEvent => {
          // handle the change event
        }
      )
  }
```

**Comment by ma2ciek** [comment] 2019-04-15 08:41
I've just released the new version which fixes the problem. See https://github.com/ckeditor/ckeditor5-angular/issues/78#issuecomment-481164036 for the correct imports. (old ones are still being supported).

**Comment by andycrulez** [comment] 2019-05-03 09:33
this works now great for me as expected.
thank you for the release.
