### ISSUE TITLE
ckeditor-cloudinary-uploader-adapter. It was not possible to load the plugin. 

### ISSUE THREAD

**Issue by MrBandaruk** [ckeditor/ckeditor5-angular#142] opened 2019-10-08 22:39 UTC
Hello. I've added **ckeditor-cloudinary-uploader-adapter** plugin to ckeditor by following [this tutorial](https://medium.com/swlh/a-detailed-approach-of-setting-up-ckeditor-with-angular-e546610157ba) and it works fine but after some time I got this errors:

![image](https://user-images.githubusercontent.com/22433209/66438264-7beb7580-ea2c-11e9-9185-f457ee4e2a06.png)

Here is my config:
```typescript
import * as BlockEditor from '@ckeditor/ckeditor5-build-balloon';
import { CloudinaryImageUploadAdapter } from 'ckeditor-cloudinary-uploader-adapter';

public textEditor = BlockEditor;
  public textConfig = {
    extraPlugins: [ this.TheUploadAdapterPlugin ],
    toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'blockQuote', 'numberedlist', 'bulletedlist', 'mediaembed', 'inserttable']
  }

  TheUploadAdapterPlugin(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = (loader) => {
      return new CloudinaryImageUploadAdapter(loader, '...', '...');
    };
  }
```

Error will disappear if I commet `extraPlugins` part.

**Comment by ma2ciek** [comment] 2019-10-11 12:33
Hi @MrBandaruk,

It's hard to tell what exactly can cause this problem. The `ckeditor-cloudinary-uploader-adapter` is not an official package, nor the tutorial.

Does this error occur after an upload, on the start of the editor or after a random amount of time? Looking at the stack trace it looks like some plugin has a problem to initialize. But it's hard to tell which, because the code is minified. Do you initialize an empty editor?

**Comment by ma2ciek** [comment] 2019-10-11 12:39
https://medium.com/@alexgerlach90/hey-good-job-but-i-get-2-errors-58eb6b83b69d - it looks like the problem is on the plugin side, thus I'm closing the issue on the `ckeditor5-angular` side.

**Closed by ma2ciek** 2019-10-11 12:39 UTC
Labels: pending:feedback
