### ISSUE TITLE
New release (1.1.1) breaking prod build

### ISSUE THREAD

**Issue by vvemuru** [ckeditor/ckeditor5-angular#153] opened 2019-10-31 20:31 UTC
Hello,

The latest release this morning broke the prod builds in Angular. We are on Angular 7.2.15 and kept running into the following error:

ERROR in ./node_modules/@ckeditor/ckeditor5-angular/fesm5/ckeditor-ckeditor5-angular.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
at isAngularDecoratorMetadataExpression (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
at checkNodeForDecorators (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
at visitNodes (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16144:30)
at Object.forEachChild (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16370:24)
at checkNodeForDecorators (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
at visitNode (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
at Object.forEachChild (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16265:21)
at checkNodeForDecorators (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
at visitNode (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
at Object.forEachChild (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16322:24)
at checkNodeForDecorators (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
at visitNode (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
at Object.forEachChild (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16333:24)
at checkNodeForDecorators (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
at visitNode (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
at Object.forEachChild (C:\angular\angular-apps\standards-works\branches\v1_0_DEV\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16229:21)

**Comment by juhil1** [comment] 2019-11-01 13:13
Hello,

I am facing the same issue.

I am on Angular 5.0.0

**Comment by etonyali** [comment] 2019-11-01 18:18
This is pretty urgent

**Comment by slampunk** [comment] 2019-11-02 07:02
Ran into the same issue during a production deployment. Downgrading to 1.1.0 fixed my issue.

I'm on Angular 7.2.

`package.json` lists Angular 8 as a dependency, so if there's am upstream change from Angular 7 -> 8 that triggers this specific issue, `ckeditor5-angular`'s README.md for 1.1.1 should be updated to note said change.

**Comment by kennethross** [comment] 2019-11-04 04:25
Im on Angular 8.0. Im having the same error aswell when deploying to production.

**Comment by kennethross** [comment] 2019-11-04 04:27
> Ran into the same issue during a production deployment. Downgrading to 1.1.0 fixed my issue.
> 
> I'm on Angular 7.2.
> 
> `package.json` lists Angular 8 as a dependency, so if there's am upstream change from Angular 7 -> 8 that triggers this specific issue, `ckeditor5-angular`'s README.md for 1.1.1 should be updated to note said change.

still run the same error when downgrade to 1.1.0

**Comment by ma2ciek** [comment] 2019-11-04 08:00
Hi,

Sorry for the issue, I'll try to fix it as soon as possible.

> package.json lists Angular 8 as a dependency,

Yep, but that's an internal (dev) dependency only of this package, we release the package only with the peerDependencies pointing the Angular.

The issue was probably caused by upgrading the `@angular-devkit`, which seems pretty weird to me, as upgrading it caused the BC for older versions. I'll check it to be 100% sure.

**Comment by ma2ciek** [comment] 2019-11-04 08:02
> still run the same error when downgrade to 1.1.0

Did you use the `"1.1.0" to point the exact version and not the "^1.1.0"?

**Comment by ma2ciek** [comment] 2019-11-04 08:25
To be sure as I can't easily reproduce it, this happens if you just run the `ng build --prod`?

**Comment by ma2ciek** [comment] 2019-11-04 09:11
Ok, I've found out that the `ng-packagr@5` incorrectly compiles the library for the `ng build --prod` 😞It seems that the https://github.com/ckeditor/ckeditor5-angular/issues/96 should have higher priority.

**Comment by ma2ciek** [comment] 2019-11-04 09:36
I've just released the https://github.com/ckeditor/ckeditor5-angular/releases/tag/v1.1.2 version that should fix this problem.

**Comment by ma2ciek** [comment] 2019-11-04 09:38
It's closed by https://github.com/ckeditor/ckeditor5-angular/commit/55788f58a642acd81e62c16184f34787fe4c6761.

Please, update your `@ckeditor/ckeditor5-angular` package to the latest version.

**Closed by ma2ciek** 2019-11-04 09:38 UTC
Labels: status:confirmed, type:bug
